/**
 * Reusable OpenAPI schemas for domain entities and common envelopes.
 * Secrets (passwordHash, reset token hashes, API keys) are never documented as response fields.
 */

export const schemaComponents = {
  ApiError: {
    type: "object",
    required: ["message"],
    properties: {
      message: { type: "string" },
      code: { type: "string", description: "Optional machine-readable error code" },
      details: { description: "Optional validation/details payload" },
    },
  },

  UserRole: {
    type: "string",
    enum: [
      "PLATFORM_OWNER",
      "SUPER_ADMIN",
      "ADMIN",
      "BRANCH_MANAGER",
      "MANAGER",
      "SUPERVISOR",
      "RECEPTIONIST",
      "MECHANIC",
    ],
  },

  PermissionKey: {
    type: "string",
    enum: [
      "DASHBOARD",
      "JOB_CARDS",
      "JOB_CARD_PRICING",
      "BOOKINGS",
      "PICKUP_DROP",
      "QUOTATIONS",
      "APPOINTMENTS",
      "CUSTOMERS",
      "MEMBERSHIP",
      "VEHICLES",
      "REMINDERS",
      "FOLLOW_UPS",
      "REFERRALS",
      "BILLING",
      "REPORTS",
      "CASH_BANK",
      "PARTIES",
      "SHARED_LEDGER",
      "EXPENSES",
      "VENDORS",
      "STAFF",
      "ATTENDANCE",
      "PAYROLL",
      "SERVICES",
      "INVENTORY",
      "BRANCHES",
      "PERFORMANCE",
      "MECHANICS",
      "ANALYTICS",
      "ADVANCED_REPORTS",
      "ACTIVITY",
      "MESSAGES",
      "SETTINGS",
    ],
  },

  User: {
    type: "object",
    description: "Staff user (password hash and reset-token fields are never returned)",
    required: ["id", "name", "email", "phone", "role", "branchId", "organizationId", "isActive"],
    properties: {
      id: { type: "string" },
      name: { type: "string" },
      email: { type: "string", format: "email" },
      phone: { type: "string" },
      employeeCode: { type: "string", nullable: true },
      role: { $ref: "#/components/schemas/UserRole" },
      branchId: { type: "string" },
      organizationId: { type: "string" },
      avatar: { type: "string", nullable: true },
      isActive: { type: "boolean" },
      emailVerified: { type: "boolean" },
      attendancePin: { type: "string", nullable: true },
      totalJobsCompleted: { type: "integer", nullable: true },
      totalIncentiveEarned: { type: "integer", nullable: true },
      birthday: { type: "string", nullable: true },
      anniversary: { type: "string", nullable: true },
      permissions: { type: "array", items: { $ref: "#/components/schemas/PermissionKey" } },
      mustChangePassword: { type: "boolean" },
      lastLoginAt: { type: "string", format: "date-time", nullable: true },
    },
  },

  Staff: {
    description: "Alias for staff User records managed via /api/users",
    allOf: [{ $ref: "#/components/schemas/User" }],
  },

  Branch: {
    type: "object",
    required: ["id", "name", "address", "phone", "isActive"],
    properties: {
      id: { type: "string" },
      name: { type: "string" },
      address: { type: "string" },
      phone: { type: "string", description: "10-digit mobile" },
      isActive: { type: "boolean" },
      qrCodeId: { type: "string", nullable: true },
      code: { type: "string", nullable: true },
      city: { type: "string", nullable: true },
      state: { type: "string", nullable: true },
      pincode: { type: "string", nullable: true },
      email: { type: "string", nullable: true },
      managerName: { type: "string", nullable: true },
      managerPhone: { type: "string", nullable: true },
      organizationId: { type: "string" },
    },
  },

  Customer: {
    type: "object",
    required: ["id", "name", "phone", "email", "address", "referralCode"],
    properties: {
      id: { type: "string" },
      name: { type: "string" },
      phone: { type: "string" },
      email: { type: "string" },
      address: { type: "string" },
      referralCode: { type: "string" },
      referredBy: { type: "string", nullable: true },
      totalVisits: { type: "integer" },
      rewardPoints: { type: "integer" },
      walletBalance: { type: "number" },
      lastVisitDate: { type: "string", nullable: true },
      isInactive: { type: "boolean" },
      emailVerified: { type: "boolean" },
      createdAt: { type: "string", format: "date-time" },
    },
  },

  VehicleSegment: {
    type: "string",
    enum: ["HATCHBACK", "SEDAN", "SUV", "LUXURY", "MUV", "COMPACT_SUV", "BIKE"],
  },

  FuelType: {
    type: "string",
    enum: ["PETROL", "DIESEL", "CNG", "ELECTRIC", "HYBRID"],
  },

  Vehicle: {
    type: "object",
    required: [
      "id",
      "customerId",
      "customerName",
      "registrationNumber",
      "make",
      "model",
      "segment",
      "fuelType",
      "color",
      "year",
    ],
    properties: {
      id: { type: "string" },
      customerId: { type: "string" },
      customerName: { type: "string" },
      registrationNumber: { type: "string" },
      make: { type: "string" },
      model: { type: "string" },
      segment: { $ref: "#/components/schemas/VehicleSegment" },
      variant: { type: "string", nullable: true },
      fuelType: { $ref: "#/components/schemas/FuelType" },
      color: { type: "string" },
      year: { type: "integer" },
      notes: { type: "string", nullable: true },
      previousOwners: { type: "array", items: {}, nullable: true },
    },
  },

  ServiceItem: {
    type: "object",
    properties: {
      id: { type: "string" },
      jobCardId: { type: "string" },
      serviceCatalogId: { type: "string" },
      name: { type: "string" },
      price: { type: "number" },
      catalogPrice: { type: "number" },
      isCustomPrice: { type: "boolean" },
      priceSource: { type: "string", enum: ["CATALOG", "CUSTOM", "MEMBERSHIP"] },
      isCompleted: { type: "boolean" },
      durationMinutes: { type: "integer" },
    },
  },

  JobCard: {
    type: "object",
    description: "Stored in AppJsonRow collection `jobCards` (passthrough allows additional fields)",
    required: [
      "id",
      "jobNumber",
      "branchId",
      "customerId",
      "customerName",
      "customerPhone",
      "vehicleId",
      "vehicleRegNumber",
      "vehicleMakeModel",
      "status",
      "services",
      "estimatedAmount",
    ],
    properties: {
      id: { type: "string" },
      jobNumber: { type: "string" },
      branchId: { type: "string" },
      customerId: { type: "string" },
      customerName: { type: "string" },
      customerPhone: { type: "string" },
      vehicleId: { type: "string" },
      vehicleRegNumber: { type: "string" },
      vehicleMakeModel: { type: "string" },
      vehicleSegment: { $ref: "#/components/schemas/VehicleSegment" },
      mechanicId: { type: "string" },
      mechanicName: { type: "string" },
      status: {
        type: "string",
        enum: [
          "RECEIVED",
          "INSPECTION",
          "AWAITING_SERVICE",
          "QUALITY_CHECK",
          "READY",
          "DELIVERED",
          "CANCELLED",
        ],
      },
      services: { type: "array", items: { $ref: "#/components/schemas/ServiceItem" } },
      estimatedAmount: { type: "number" },
      incentivePercent: { type: "number" },
      incentiveAmount: { type: "number" },
      quotationId: { type: "string" },
      appointmentId: { type: "string" },
      bookingId: { type: "string" },
      notes: { type: "string" },
      expectedDelivery: { type: "string" },
      inspectionPhotos: { type: "array", items: { type: "object" } },
    },
    additionalProperties: true,
  },

  Appointment: {
    type: "object",
    description:
      "Stored in AppJsonRow collection `appointments`. Bookings use kind=BOOKING (BK-*) within the same collection.",
    required: [
      "id",
      "bookingId",
      "customerId",
      "customerName",
      "customerPhone",
      "vehicleId",
      "vehicleRegNumber",
      "vehicleMakeModel",
      "serviceType",
      "date",
      "time",
      "status",
      "whatsappSent",
      "createdAt",
    ],
    properties: {
      id: { type: "string" },
      bookingId: { type: "string" },
      appointmentNumber: { type: "string" },
      kind: { type: "string", enum: ["BOOKING", "APPOINTMENT"] },
      branchId: { type: "string" },
      customerId: { type: "string" },
      customerName: { type: "string" },
      customerPhone: { type: "string" },
      vehicleId: { type: "string" },
      vehicleRegNumber: { type: "string" },
      vehicleMakeModel: { type: "string" },
      serviceType: { type: "string" },
      mechanicId: { type: "string" },
      mechanicName: { type: "string" },
      date: { type: "string", description: "yyyy-MM-dd" },
      time: { type: "string" },
      status: {
        type: "string",
        enum: [
          "SCHEDULED",
          "CONFIRMED",
          "IN_PROGRESS",
          "COMPLETED",
          "CANCELLED",
          "NOT_ATTENDED",
        ],
      },
      jobCardId: { type: "string" },
      notes: { type: "string" },
      whatsappSent: { type: "boolean" },
      reminderSent: { type: "boolean" },
      createdAt: { type: "string" },
      priceGrandTotal: { type: "number" },
      advancePaid: { type: "number" },
      customerAddress: { type: "string" },
    },
    additionalProperties: true,
  },

  Booking: {
    description:
      "Customer booking (Appointment with kind=BOOKING). Persist via `/api/collections/appointments`.",
    allOf: [{ $ref: "#/components/schemas/Appointment" }],
  },

  Payment: {
    type: "object",
    required: ["id", "invoiceId", "amount", "method", "paidAt"],
    properties: {
      id: { type: "string" },
      invoiceId: { type: "string" },
      amount: { type: "number" },
      method: { type: "string", enum: ["CASH", "UPI", "CARD", "WALLET"] },
      referenceNumber: { type: "string" },
      paidAt: { type: "string" },
    },
  },

  InvoiceLineItem: {
    type: "object",
    properties: {
      id: { type: "string" },
      description: { type: "string" },
      type: { type: "string", enum: ["SERVICE", "PARTS", "LABOR", "OTHER"] },
      quantity: { type: "number" },
      unitPrice: { type: "number" },
      total: { type: "number" },
      hsnSac: { type: "string" },
      lineDiscount: { type: "number" },
    },
  },

  Invoice: {
    type: "object",
    description: "Stored in AppJsonRow collection `invoices`",
    required: [
      "id",
      "invoiceNumber",
      "jobCardId",
      "customerId",
      "customerName",
      "customerPhone",
      "status",
      "subtotal",
      "taxRate",
      "taxAmount",
      "grandTotal",
      "lineItems",
    ],
    properties: {
      id: { type: "string" },
      invoiceNumber: { type: "string" },
      jobCardId: { type: "string" },
      jobNumber: { type: "string" },
      customerId: { type: "string" },
      customerName: { type: "string" },
      customerPhone: { type: "string" },
      vehicleRegNumber: { type: "string" },
      lineItems: { type: "array", items: { $ref: "#/components/schemas/InvoiceLineItem" } },
      subtotal: { type: "number" },
      taxRate: { type: "number" },
      taxAmount: { type: "number" },
      discountAmount: { type: "number" },
      grandTotal: { type: "number" },
      status: { type: "string", enum: ["DRAFT", "ISSUED", "PARTIALLY_PAID", "PAID"] },
      payments: { type: "array", items: { $ref: "#/components/schemas/Payment" } },
      createdAt: { type: "string" },
    },
    additionalProperties: true,
  },

  Quotation: {
    type: "object",
    description: "Stored in AppJsonRow collection `quotations`",
    required: [
      "id",
      "quotationNumber",
      "customerId",
      "customerName",
      "customerPhone",
      "status",
      "services",
      "subtotal",
      "taxRate",
      "taxAmount",
      "grandTotal",
    ],
    properties: {
      id: { type: "string" },
      quotationNumber: { type: "string" },
      customerId: { type: "string" },
      customerName: { type: "string" },
      customerPhone: { type: "string" },
      vehicleId: { type: "string" },
      vehicleRegNumber: { type: "string" },
      vehicleMakeModel: { type: "string" },
      services: { type: "array", items: { type: "object" } },
      subtotal: { type: "number" },
      taxRate: { type: "number" },
      taxAmount: { type: "number" },
      grandTotal: { type: "number" },
      status: {
        type: "string",
        enum: ["DRAFT", "SENT", "APPROVED", "REJECTED", "CONVERTED"],
      },
      convertedToJobCardId: { type: "string" },
      validUntil: { type: "string" },
      createdAt: { type: "string" },
      updatedAt: { type: "string" },
    },
    additionalProperties: true,
  },

  PickupDropRequest: {
    type: "object",
    description: "Stored in AppJsonRow collection `pickupDropRequests`",
    required: [
      "id",
      "jobCardId",
      "jobNumber",
      "type",
      "customerName",
      "address",
      "scheduledTime",
      "status",
      "branchId",
      "createdAt",
      "updatedAt",
    ],
    properties: {
      id: { type: "string" },
      jobCardId: { type: "string" },
      jobNumber: { type: "string" },
      type: { type: "string", enum: ["PICKUP", "DROP"] },
      customerName: { type: "string" },
      customerPhone: { type: "string" },
      vehicleMakeModel: { type: "string" },
      vehicleRegNumber: { type: "string" },
      address: { type: "string" },
      scheduledTime: { type: "string" },
      driverId: { type: "string" },
      driverName: { type: "string" },
      status: {
        type: "string",
        enum: ["PENDING", "DRIVER_ASSIGNED", "PICKED_UP", "IN_SERVICE", "DELIVERED"],
      },
      notes: { type: "string" },
      branchId: { type: "string" },
      createdAt: { type: "string" },
      updatedAt: { type: "string" },
    },
    additionalProperties: true,
  },

  AppSettings: {
    type: "object",
    description: "Singleton AppJsonRow `appSettings` (entityId=default). Shape is client-driven.",
    properties: {
      businessName: { type: "string" },
      logoUrl: { type: "string" },
      brandColor: { type: "string" },
      gstin: { type: "string" },
      address: { type: "string" },
      phone: { type: "string" },
      email: { type: "string" },
      taxRate: { type: "number" },
      termsAndConditions: { type: "string" },
    },
    additionalProperties: true,
  },

  Organization: {
    type: "object",
    description: "Studio-safe organization view (no internalNotes)",
    properties: {
      id: { type: "string" },
      name: { type: "string" },
      slug: { type: "string", nullable: true },
      isActive: { type: "boolean" },
      planCode: {
        type: "string",
        enum: ["STARTER", "GROWTH", "BUSINESS", "ENTERPRISE", "CUSTOM"],
      },
      planName: { type: "string" },
      status: {
        type: "string",
        enum: ["ACTIVE", "PAST_DUE", "EXPIRED", "CANCELLED"],
      },
      limits: {
        type: "object",
        properties: {
          maxBranches: { type: "integer", nullable: true },
          maxStaff: { type: "integer", nullable: true },
          maxCustomers: { type: "integer", nullable: true },
        },
      },
      contactUsUrl: { type: "string", nullable: true },
      contactPhone: { type: "string", nullable: true },
      upgradeUrl: { type: "string", nullable: true },
      branchCount: { type: "integer" },
      maxBranches: { type: "integer", nullable: true },
    },
  },

  Party: {
    type: "object",
    required: ["id", "kind", "name"],
    properties: {
      id: { type: "string" },
      kind: { type: "string", enum: ["customer", "supplier"] },
      name: { type: "string" },
      category: { type: "string" },
      mobile: { type: "string" },
      email: { type: "string" },
      gstin: { type: "string" },
      pan: { type: "string" },
      billingAddress: { type: "string" },
      shippingAddress: { type: "string" },
      openingBalance: { type: "number" },
      openingBalanceSide: { type: "string", enum: ["toCollect", "toPay"] },
      creditPeriodDays: { type: "integer" },
      creditLimit: { type: "number" },
      contactPersonName: { type: "string" },
      dateOfBirth: { type: "string" },
      customerId: { type: "string" },
      vendorKey: { type: "string" },
      bankAccounts: { type: "array", items: { type: "object" } },
      shippingAddresses: { type: "array", items: { type: "object" } },
      customFields: { type: "array", items: { type: "object" } },
    },
    additionalProperties: true,
  },

  AttendanceRecord: {
    type: "object",
    properties: {
      id: { type: "string" },
      staffId: { type: "string" },
      staffName: { type: "string" },
      staffRole: { $ref: "#/components/schemas/UserRole" },
      branchId: { type: "string" },
      date: { type: "string", description: "yyyy-MM-dd (staff local)" },
      checkIn: { type: "string", nullable: true, description: "HH:mm" },
      checkOut: { type: "string", nullable: true },
      durationMinutes: { type: "integer", nullable: true },
      status: { type: "string", enum: ["PRESENT", "ABSENT", "LATE", "HALF_DAY"] },
      qrScanned: { type: "boolean" },
    },
  },

  AuthSuccess: {
    type: "object",
    required: ["accessToken", "user"],
    properties: {
      accessToken: {
        type: "string",
        description: "JWT — pass as `Authorization: Bearer <token>`. Not logged or stored in docs.",
      },
      user: { $ref: "#/components/schemas/User" },
      branch: { allOf: [{ $ref: "#/components/schemas/Branch" }], nullable: true },
    },
  },

  CollectionName: {
    type: "string",
    description: "Registered AppJsonRow collection",
    enum: [
      "jobCards",
      "invoices",
      "quotations",
      "appointments",
      "expenses",
      "activityLogs",
      "serviceReminders",
      "walletTransactions",
      "serviceCatalog",
      "parts",
      "stockMovements",
      "productPurchases",
      "followUps",
      "serviceCategories",
      "notifications",
      "pickupDropRequests",
      "communications",
      "dashboardStats",
      "expenseMeta",
      "cashBank",
      "payroll",
      "membership",
      "appSettings",
      "referralProgram",
      "balanceSheetManual",
      "highEndServices",
      "reportSchedules",
      "vehicleCatalog",
    ],
  },

  OkOk: {
    type: "object",
    properties: { ok: { type: "boolean", example: true } },
  },
} as const;
